package study.hry.web.plugin.support;

import java.util.List;
import java.util.Map;

public class JsTreeNode {
	private String id; // will be autogenerated if omitted
	private String text; // node text
	private String icon; // string for custom
	private List<JsTreeNode> children; // children : [] // array of strings or
										// objects
	private Map<String, String> li_attr; // li_attr : {} // attributes for the
											// generated LI node
	private Map<String, String> a_attr; // a_attr : {} // attributes for the
										// generated A node
	private State state;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public List<JsTreeNode> getChildren() {
		return children;
	}

	public void setChildren(List<JsTreeNode> children) {
		this.children = children;
	}

	public Map<String, String> getLi_attr() {
		return li_attr;
	}

	public void setLi_attr(Map<String, String> li_attr) {
		this.li_attr = li_attr;
	}

	public Map<String, String> getA_attr() {
		return a_attr;
	}

	public void setA_attr(Map<String, String> a_attr) {
		this.a_attr = a_attr;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public static class State {
		private boolean opened; // : boolean // is the node open
		private boolean disabled; // : boolean // is the node disabled
		private boolean selected; // : boolean // is the node selected

		public boolean isOpened() {
			return opened;
		}

		public void setOpened(boolean opened) {
			this.opened = opened;
		}

		public boolean isDisabled() {
			return disabled;
		}

		public void setDisabled(boolean disabled) {
			this.disabled = disabled;
		}

		public boolean isSelected() {
			return selected;
		}

		public void setSelected(boolean selected) {
			this.selected = selected;
		}

	}
	
	public static void main(String[] args) {
		JsTreeNode obj = new JsTreeNode();
//		String jsonString = JSON.toJSONString(obj);
	}
}
